### ISSUE TITLE
yield just nested elements

### ISSUE THREAD

**Issue by der-flo** [pitr-ch/htmless#3]
**Introduction:** I'm actually trying to develop a framework for UI components for one of our complex rails projects. It's somewhat similar to [Cells](http://trailblazer.to/gems/cells/), but allows you to specify multiple blocks of markup code as parameters for such a component.

Capturing multiple blocks seems non-trivial and already opened a request in the haml repo: https://github.com/haml/haml/issues/931
Now I'm testing many, many templating systems against my use case. (Spoiler: https://github.com/apotonick/erbse allows this but has an ugly syntax.)

**Problem:** `yield` returns all content instead of just the nested one.

**Example:** (reduced to the problem)

```ruby
require 'htmless'

class ComponentContext
  def my_block
    puts '... my_block captured:'
    puts yield
    puts '......................'
    puts
    nil
  end
end

class MyBuilder < Htmless::Formatted
  def ui_component
    ctx = ComponentContext.new
    content = yield ctx

    puts '... ui_component captured:'
    puts content
    puts '..........................'

    nil
  end
end

html = MyBuilder.new.go_in do
  body do
    ui_component do |comp|
      text 'component content'

      comp.my_block do
        text 'my_block content'
      end
    end
  end
end.to_html
puts '---'
puts html
```

**Output:**

```
... my_block captured:

<body>component contentmy_block content
......................

... ui_component captured:

..........................
---

<body>component contentmy_block content
</body>
```

The output shows that `my_block` not only captures the nested text `my_block content` but everything else inside the Builder block.
The `yield` further outside in `ui_component` captures nothing of the markup.

@pitr-ch: Do you have a tip for me?

**Comment by pitr-ch** [comment]
Hi, for performance reasons the builder works as a buffer, as a tag method is called on the builder its string representation is immediately appended to the buffer. There is no tree-like object representation of the tags. if you need to capture a subpart (a tag and its children) of the whole tree you can render the part with another builder and get the captured result with to_html at the end, the captured part has to be inserted in the parent builder with `raw` method for the whole tree to contain the captured piece as well. I hope it helps, and please don't hesitate if you have further questions.

**Comment by der-flo** [comment]
Thanks for your assessment. I'll check whether using multiple builders fits my use-case, but I have doubts.

**Comment by pitr-ch** [comment]
If you have a moment please share your findings, I would be interested to understand what use-case is missing in the gem.
